import { useEffect } from 'react';
import { Footer } from '@/components/newDesign/home/footer';
import { Navbar } from '@/components/newDesign/home/navbar';

export function Terms() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[hsl(220,20%,98%)] flex flex-col">
      <Navbar />

      <main className="flex-1 pt-[107px]">
        {/* Hero header */}
        <section className="relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-[hsl(221,91%,60%)]/[0.04] to-transparent pointer-events-none" />
          <div className="max-w-3xl mx-auto px-6 pt-16 pb-10 text-center relative">
            <span className="inline-flex items-center px-3.5 py-1 rounded-full text-xs bg-[hsl(221,91%,60%)]/10 text-[hsl(221,91%,60%)] mb-5">
              Legal
            </span>
            <h1 className="text-4xl lg:text-5xl text-[hsl(222,22%,15%)] mb-3 tracking-tight font-[family-name:var(--font-serif)]">
              Terms of Service
            </h1>
            <p className="text-lg text-[hsl(222,12%,45%)] max-w-lg mx-auto leading-relaxed">
              The terms that govern your use of Screna.ai
            </p>
            <div className="flex items-center justify-center gap-2 mt-4 text-sm text-[hsl(222,12%,55%)]">
              <span>Effective: March 21, 2026</span>
              <span className="w-1 h-1 rounded-full bg-[hsl(222,12%,70%)]" />
              <span>Last Updated: March 21, 2026</span>
            </div>
          </div>
        </section>

        {/* Content area */}
        <section className="max-w-4xl mx-auto px-6 pb-24">
          <div className="bg-white rounded-2xl border border-[hsl(220,16%,90%)] shadow-sm overflow-hidden">
            <div className="p-8 md:p-10">
              <div className="prose prose-slate max-w-none">
                <p className="text-[hsl(222,12%,45%)] mb-4">
                  These Terms of Service ("Terms") govern your access to and use of Screna.ai and any related
                  websites, applications, products, community features, content, and services operated by
                  Screna Tech Inc. ("Company," "we," "us," or "our") (collectively, the "Service").
                </p>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  By clicking "Confirm" (or any similar button indicating acceptance), you acknowledge that you
                  have read, understood, and agree to be legally bound by all terms and conditions set forth in
                  these Terms. If you do not agree to these Terms, do not click "Confirm".
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">1) Definitions</h2>
                <ul className="list-disc pl-6 mb-8 space-y-2 text-[hsl(222,12%,45%)]">
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"Account"</strong> means your registered user
                    account for the Service.
                  </li>
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"AI Features"</strong> means features that use
                    machine learning, artificial intelligence, automation, or related technologies to generate,
                    analyze, score, summarize, recommend, simulate, classify, or transform content.
                  </li>
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"AI Outputs"</strong> means any content,
                    feedback, score, evaluation, recommendation, transcript, summary, report, or other output
                    generated by or with AI Features.
                  </li>
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"Application Materials"</strong> means resumes,
                    CVs, cover letters, portfolios, job descriptions, writing samples, and similar
                    career-related materials.
                  </li>
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"Community Content"</strong> means User Content
                    posted to public or semi-public areas of the Service.
                  </li>
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"Restricted Information"</strong> means any
                    non-public, confidential, proprietary, privileged, trade secret, or contractually
                    restricted information.
                  </li>
                  <li>
                    <strong className="text-[hsl(222,22%,15%)]">"User Content"</strong> means any Content that
                    you submit, upload, post, transmit, record, publish, display, or otherwise make available
                    through or to the Service.
                  </li>
                </ul>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">2) Eligibility</h2>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  You must be at least 18 years old, or the age of majority in your jurisdiction if higher, to
                  use the Service. By using the Service, you represent and warrant that you meet the applicable
                  age requirement, you have the legal capacity to enter into these Terms, and your use of the
                  Service does not violate any applicable law, rule, regulation, contract, or policy.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  3) Accounts and Security
                </h2>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  You may need to create an Account to access some or all features of the Service. You agree to
                  provide accurate, current, and complete information; keep your information updated; maintain
                  the confidentiality of your login credentials; and notify us promptly at{' '}
                  <a
                    href="mailto:operations@screna.ai"
                    className="text-[hsl(221,91%,60%)] hover:underline"
                  >
                    operations@screna.ai
                  </a>{' '}
                  if you believe your Account has been compromised.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  4) The Service and AI Features
                </h2>
                <div className="space-y-4 mb-8">
                  <div className="border-l-4 border-l-[hsl(221,91%,60%)] pl-4">
                    <h3 className="text-lg font-semibold text-[hsl(222,22%,15%)] mb-2">
                      4.2 AI Outputs Disclaimer
                    </h3>
                    <p className="text-[hsl(222,12%,45%)] text-sm">
                      You acknowledge that AI Features are experimental and continuously evolving, and AI
                      Outputs may be inaccurate, incomplete, misleading, biased, inconsistent, offensive, or
                      otherwise unsuitable for your intended use. AI Outputs are provided for informational,
                      educational, and practice purposes only and do not constitute legal, financial, medical,
                      psychological, recruiting, hiring, immigration, employment, or career advice.
                    </p>
                  </div>

                  <div className="border-l-4 border-l-[hsl(221,91%,60%)] pl-4">
                    <h3 className="text-lg font-semibold text-[hsl(222,22%,15%)] mb-2">
                      4.3 No Guarantee of Results
                    </h3>
                    <p className="text-[hsl(222,12%,45%)] text-sm">
                      We do not guarantee any outcome from your use of the Service, including any improvement
                      in interview performance, hiring success, offer rate, compensation, job placement,
                      networking outcome, or career advancement.
                    </p>
                  </div>

                  <div className="border-l-4 border-l-[hsl(221,91%,60%)] pl-4">
                    <h3 className="text-lg font-semibold text-[hsl(222,22%,15%)] mb-2">
                      4.4 No Employment or Agency Relationship
                    </h3>
                    <p className="text-[hsl(222,12%,45%)] text-sm">
                      The Company is not an employer, recruiter, staffing agency, headhunter, or career
                      placement agency.
                    </p>
                  </div>
                </div>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  5) Recordings, Transcripts, Resume Processing, and Consent
                </h2>
                <p className="text-[hsl(222,12%,45%)] mb-4">
                  The Service may record, receive, and store your audio, video, screen, and related metadata;
                  create and store transcripts, summaries, scores, and derived evaluations; and analyze
                  recordings, speech, text, and behavioral signals for Service functionality.
                </p>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  You shall not submit, upload, post, record, or share any Restricted Information that you are
                  not authorized to disclose, including information subject to any NDA or confidentiality
                  obligation, proprietary interview questions, or internal documentation.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  6) Your Content and Permissions
                </h2>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  As between you and the Company, and subject to the rights you grant in these Terms, you
                  retain ownership of your User Content. You grant the Company a non-exclusive, worldwide,
                  royalty-free, sublicensable, and transferable license to use, host, store, reproduce,
                  process, transmit, display, modify, analyze, and create derivative works from your User
                  Content as reasonably necessary to provide and improve the Service.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">8) Acceptable Use</h2>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  You agree not to use the Service for any unlawful, harmful, deceptive, fraudulent,
                  infringing, or unauthorized purpose; reverse engineer or decompile any part of the Service;
                  or interfere with the Service or the experience of other users.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  11) Paid Plans, Billing, and Subscriptions
                </h2>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  Certain features may require payment. Subscriptions auto-renew unless cancelled. You may
                  cancel at any time through account settings; access continues for 30 days following
                  cancellation. All paid fees are non-refundable except as required by applicable law.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">15) Disclaimers</h2>
                <div className="bg-[hsl(220,20%,98%)] rounded-xl p-5 mb-8 border border-[hsl(220,16%,90%)]">
                  <p className="text-[hsl(222,22%,15%)] text-xs uppercase tracking-wide leading-relaxed">
                    To the maximum extent permitted by law, the Service, AI Features, AI Outputs, Community
                    Content, and all related content and materials are provided "as is" and "as available,"
                    without warranty of any kind, whether express, implied, statutory, or otherwise. We do not
                    warrant that AI Outputs or Community Content will be accurate, complete, reliable, lawful,
                    non-infringing, or suitable for your needs.
                  </p>
                </div>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  16) Limitation of Liability
                </h2>
                <div className="bg-[hsl(220,20%,98%)] rounded-xl p-5 mb-8 border border-[hsl(220,16%,90%)]">
                  <p className="text-[hsl(222,22%,15%)] text-xs uppercase tracking-wide leading-relaxed">
                    The total aggregate liability of the Company for all claims arising out of or relating to
                    the Service or these Terms shall not exceed the greater of: (a) the total amount you paid
                    to us for the Service in the 12 months immediately preceding the event giving rise to the
                    claim; or (b) USD $100 if you have not paid us.
                  </p>
                </div>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  19) Governing Law and Venue
                </h2>
                <p className="text-[hsl(222,12%,45%)] mb-8">
                  These Terms are governed by the laws of the State of Delaware, without regard to its
                  conflict-of-laws principles.
                </p>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">
                  20) Dispute Resolution; Class Action Waiver
                </h2>
                <p className="text-[hsl(222,12%,45%)] mb-4">
                  Any dispute will be resolved through binding arbitration on an individual basis in the State
                  of Delaware, except that either party may bring an individual claim in small claims court if
                  it qualifies.
                </p>
                <div className="bg-[hsl(221,91%,60%)]/5 rounded-xl p-5 mb-8 border border-[hsl(221,91%,60%)]/20">
                  <p className="text-[hsl(222,22%,15%)] text-xs uppercase tracking-wide font-semibold leading-relaxed">
                    You and the Company waive any right to participate in a class action, class arbitration,
                    or representative action.
                  </p>
                </div>

                <h2 className="text-2xl font-semibold text-[hsl(222,22%,15%)] mt-8 mb-4">22) Contact</h2>
                <div className="bg-[hsl(220,20%,98%)] rounded-xl p-5 mb-8">
                  <p className="text-[hsl(222,12%,45%)] mb-2">
                    <strong className="text-[hsl(222,22%,15%)]">Legal:</strong>{' '}
                    <a
                      href="mailto:Attorney@tslawfirm.co"
                      className="text-[hsl(221,91%,60%)] hover:underline"
                    >
                      Attorney@tslawfirm.co
                    </a>
                  </p>
                  <p className="text-[hsl(222,12%,45%)] mb-2">
                    <strong className="text-[hsl(222,22%,15%)]">Support:</strong>{' '}
                    <a
                      href="mailto:operations@screna.ai"
                      className="text-[hsl(221,91%,60%)] hover:underline"
                    >
                      operations@screna.ai
                    </a>
                  </p>
                  <p className="text-[hsl(222,12%,45%)]">
                    <strong className="text-[hsl(222,22%,15%)]">Address:</strong> 42 HANSOM RD, BASKING RIDGE,
                    NJ 07920
                  </p>
                </div>

                <div className="pt-6 border-t border-[hsl(220,16%,90%)] mt-6">
                  <p className="text-xs text-[hsl(222,12%,55%)] text-center">
                    Last updated: March 21, 2026
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
